# Site settings
title: The Big Blue House
description: Welcome to the The Big Blue House.
baseurl: ""
url: "http://thebigbluehouse.com"

# Collections
collections:
  work:
    title: Work
    output: true

# Default settings
defaults:
  - scope:
      path: work
      type: work
    values:
      layout: page

# Build settings.
markdown: kramdown

# Include hidden directories.
include:
  - _pages

# Exclude directories and files
exclude:
  - _misc
  - node_modules

# Environments in Jekyll - http://www.petethompson.net/blog/web/2015/02/28/environments-in-jekyll/
environment: development
