# Site settings
title: The Big Blue House
email: https://github.com/jrockowitz/
description: >
  Welcome to the The Big Blue House.
baseurl: ""
url: "http://jrockowitz.github.io/" # the base hostname & protocol for your site
twitter_username: jrockowitz
github_username:  jrockowitz

# Collections
collections:
  work:
    title: Work
    output: true

defaults:
  - scope:
      path: work
      type: work
    values:
      layout: page

# Build settings
markdown: kramdown

include:
  - _pages

# Exclude directories and files
exclude:
  - node_modules

# Environments in Jekyll - http://www.petethompson.net/blog/web/2015/02/28/environments-in-jekyll/
environment: development
