# Site settings
title: The Big Blue House
email: https://github.com/jrockowitz/
description: >
  Welcome to the The Big Blue House.
baseurl: ""
url: "http://thebigbluehouse.com/"

# Collections
collections:
  work:
    title: Work
    output: true

defaults:
  - scope:
      path: work
      type: work
    values:
      layout: page

# Build settings
markdown: kramdown

include:
  - _pages
  - images
  - images_srcset
  - vendor

# Exclude directories and files
exclude:
  - _misc
  - node_modules

# Environments in Jekyll - http://www.petethompson.net/blog/web/2015/02/28/environments-in-jekyll/
environment: production
