# Site settings
title: The Big Blue House
subtitle: Jacob Rockowitz
description: >
  I grew up in a big blue house. The big blue house is a central theme to my artwork. Sitting in front of a computer in the basement of this big blue house is where I learned how to build websites so it seem fitting to call my company, which I incorporated in 2000, 'The Big Blue House Production'.
baseurl: ""
url: "http://thebigbluehouse.com"

# Collections
collections:
  work:
    title: Work
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: work
      type: work
    values:
      layout: "page"

# Build
markdown: kramdown

# Include hidden directories
include:
  - _pages

# Exclude directories
exclude:
  - _misc
  - node_modules

# Gem (for GitHub Pages)
gems:
  # Sitemaps for GitHub Pages - https://help.github.com/articles/sitemaps-for-github-pages/
  - jekyll-sitemap
  # Redirects on GitHub Pages - https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Environments in Jekyll - http://www.petethompson.net/blog/web/2015/02/28/environments-in-jekyll/
environment: production
